### ISSUE TITLE
502 Bad Gateway nginx Problem while creating a new policy

### ISSUE THREAD

**Issue by Saunak94** [eclipse/ditto-examples#4]
i am new to ditto, i was following the step to create  IoT-Device connected directly to Ditto via MQTT 
( https://github.com/eclipse/ditto-examples/tree/master/mqtt-bidirectional ) 
 When i tried to create a policy by using Postman i got an error saying 502 Bad Gateway nginx ,
 i first installed eclipse ditto, then i run eclipse Mosquitto on docker container  on my machine , i am using windows 10. 
please suggest me how can i resolve it?

**Comment by ffendt** [comment]
Hey, sorry for the late response. I think i'll need some more help from your side to be able to give you advice how to resolve your problem:

1. Did you start Eclipse Ditto using `docker-compose` as described in the [Getting started section](https://github.com/eclipse/ditto#getting-started) of Ditto?

2. Can you verify all containers are running (using `docker ps`)?
Following containers should be running:
`nginx:1.13-alpine`
`eclipse/ditto-connectivity:latest`
`eclipse/ditto-gateway:latest`
`eclipse/ditto-things-search:latest`
`eclipse/ditto-things:latest`
`eclipse/ditto-concierge:latest`
`swaggerapi/swagger-ui:v2.2.9`
`eclipse/ditto-policies:latest`
`mongo:3.4`

3. Can you see exceptions in the logs (`docker-compose logs` )?

**Comment by saunakasansol94** [comment]
Hi i have solved the problem partially... the problem i was getting because the images were not properly getting closed when ever i was doing docker-compose down. the problem was actually the containers were getting existed due to some reason .. i removed all the containers by docker rm (container-id)  then i again started the compose file by docker-compose up and now it its working fine.

the docker ps-a  file now shows  like this :  
![docker ps -a](https://user-images.githubusercontent.com/35859990/50677252-cc0d5580-101e-11e9-8b38-af63df568b0c.PNG)
